- name: install EPEL repo
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10

- name: import EPEL key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present

- name: Install MariaDB package
  yum: name={{ item }} state=installed
  with_items:
   - mariadb-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python

- name: Create Mysql configuration file
  template: src={{ansible_os_family}}/my.cnf.j2 dest=/etc/my.cnf
  notify: 
  - restart mariadb
  
- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775
  
- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

- name: Install nginx
  yum: name=nginx state=present enablerepo=epel
  tags: nginx

- name: copy nginx configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx
  tags: nginx

- name: enable firewalld service
  service:
    name: firewalld
    state: started
    enabled: yes
  tags: firewalld

- name: configure firewalld
  firewalld: service=http permanent=true state=enabled
  notify: restart firewalld
  tags: firewalld

- name: configure firewalld
  firewalld: service=https permanent=true state=enabled
  notify: restart firewalld
  when: wp_ssl_cert is defined
  tags: firewalld

- name: Install php-fpm and deps 
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-fpm
    - php-enchant
    - php-IDNA_Convert
    - php-mbstring
    - php-mysql
    - php-PHPMailer
    - php-process
    - php-simplepie
    - php-xml

- name: install SEManage
  yum: pkg=policycoreutils-python state=present